In [2]:
import pickle
import numpy as np
import scipy.linalg as la

In [6]:
respostas = pickle.load(open('A42921_Ficha1_Respostas.p','rb'))
respostas

{'Q001': array([[-1., -1., -1., -1.],
        [-1., -1., -1., -1.],
        [-1., -1., -1., -1.]]),
 'Q002': array([[-1., -1., -1., -1.],
        [-1., -1., -1., -1.],
        [-1., -1., -1., -1.],
        [-1., -1., -1., -1.]]),
 'Q003': array([[-1., -1., -1., -1.],
        [-1., -1., -1., -1.]]),
 'nome': 'Fábio Alexandre Cruz Silva Dias',
 'numero': 'A42921'}

## Exercício 1

In [2]:
X = np.array([[-1, -2, -4, 4, 6, 6, 2], [1, 2, 1, 0, -2, 0, -1]])
X = X.T
X

w0 = X[:3]
w1 = X[3:]

print(w0)
print(w1)

NameError: name 'np' is not defined

### a)

#### i)

In [107]:
w0mean = np.mean(w0, axis=0)
w1mean = np.mean(w1, axis=0)

'''
This is what it's doing
w0meanX = np.mean(w0[:, 0])
w0meanY = np.mean(w0[:, 1])
w1meanX = np.mean(w1[:, 0])
w1meanY = np.mean(w1[:, 1])

w0mean = np.array([w0meanX, w0meanY])
w1mean = np.array([w1meanX, w1meanY])
'''

dotProduct = np.dot(w0mean, w1mean)
dotProduct

-11.5

#### ii)

In [108]:
w0Norm = la.norm(w0mean)

'''
This is what it's doing
w0meanSquared = w0mean[0] ** 2 + w0mean[1] ** 2 #Other way: w0meanSquaredv2 = w0mean[:] ** 2
w0meanSumSquared = np.sum(w0meanSquared)
w0Norm = np.sqrt(w0meanSumSquared)
'''

print(w0Norm)

2.68741924943285


### b)

#### i)

In [109]:
X0 = np.array([[-1, -2, -4], [1, 2, 1]])
produtoMatricial = np.dot(X0, X0.T)

print(produtoMatricial)

[[21 -9]
 [-9  6]]


#### ii)

In [110]:
cov = np.cov(X0)

print(cov)

[[2.33333333 0.16666667]
 [0.16666667 0.33333333]]


### c)

#### i)

In [111]:
X1 = np.array([[4, 6, 6, 2], [0, -2, 0, -1]])

cov = np.cov(X1)
X1mean = np.mean(w1, axis=0)
produtoCovX1mean = np.dot(cov, X1mean)

print(produtoCovX1mean.T)

[16.625  -1.4375]


#### ii)

In [112]:
X0 = np.array([[-1, -2, -4], [1, 2, 1]])

cov = np.cov(X0)
X0mean = np.mean(w0, axis=0)
produtoCovX0mean = np.dot(cov, X0mean)

print(produtoCovX0mean.T)

[-5.22222222  0.05555556]


## Exercício 2

In [128]:
D = pickle.load(open('A42921_Q002_data.p','rb'))
dados = D['dados']
classes = D['trueClass']

### a)

#### i)

In [156]:
print(dados.shape)
print(classes)

numeroTotalDeAmostras = len(classes)
a = np.mean(dados, axis=0)
a.shape

b = a[classes == 0]
print(b.shape)

print(len(b) / numeroTotalDeAmostras)
print()
print()

numeroTotalAmostras = len(classes)
amostrasAlvo = np.sum(classes == 0)
print(amostrasAlvo / numeroTotalAmostras)

(2, 1950)
[4. 4. 4. ... 4. 2. 4.]
(400,)
0.20512820512820512


0.20512820512820512


#### ii)

In [184]:
cov = np.cov(dados[:, classes == 4])
cov

array([[ 1.953717  , -0.2338568 ],
       [-0.2338568 ,  1.89525009]])

### b)

#### i)

In [177]:
indiceAmostras = np.where(classes == 1)
amostras = dados[:, indiceAmostras[0]]
amostrasMedia = np.mean(amostras, axis=1)

print(amostrasMedia)

#print(indiceAmostras)
#print(amostras)

[-2.11850051 -5.27674343]


#### ii)

In [178]:
indiceAmostras = np.where(classes == 2)
amostras = dados[:, indiceAmostras[0]]
amostrasMedia = np.mean(amostras, axis=1)

print(amostrasMedia)

[-5.92557341  3.09165685]


### c)

#### i)

In [181]:
np.mean(dados, axis=1)

array([0.21781899, 0.19148105])

#### ii)

In [183]:
np.cov(dados)

array([[12.06159916,  0.36795179],
       [ 0.36795179, 11.62977501]])

### d)

#### i)

In [192]:
indiceAmostras0 = np.where(classes == 0)
indiceAmostras2 = np.where(classes == 2)

meanClass0 = np.mean(dados[:, indiceAmostras0[0]], axis=1)
meanClass2 = np.mean(dados[:, indiceAmostras2[0]], axis=1)
cov2 = np.cov(dados[:, classes == 2])

produtoMatricial = np.dot(meanClass0.T, np.dot(cov2, meanClass2))

produtoMatricial

0.19959444647157332

#### ii)

In [197]:
cov0 = np.cov(dados[:, classes== 0])
cov2 = np.cov(dados[:, classes== 2])

produtoMatricial = np.dot(cov0, cov2)
determinante = la.det(produtoMatricial)

determinante

4.241469994535395

#### iii)

In [200]:
indiceAmostras1 = np.where(classes == 1)
indiceAmostras2 = np.where(classes == 2)

meanClass1 = np.mean(dados[:, indiceAmostras1[0]], axis=1)
meanClass2 = np.mean(dados[:, indiceAmostras2[0]], axis=1)

produtoInterno = np.dot(meanClass1, meanClass2)

produtoInterno

-3.760549653539636

#### iv)

In [202]:
indiceAmostras4 = np.where(classes == 4)

meanClass4 = np.mean(dados[:, indiceAmostras4[0]], axis=1)
cov3 = np.cov(dados[:, classes == 3])

produtoInterno = np.dot(cov3, meanClass4)

produtoInterno

array([3.28230988, 3.63618569])

## Exercício 3

### a)

In [3]:
N = 20000000
X=np.random.randn(2,N)

#### i)

In [212]:
A=np.array([[8.46,-0.68],[3.06,1.88]])
m=np.array([-4, -3])
Y=np.dot(A,X)+m[:,np.newaxis]

np.cov(Y)

array([[72.04460624, 24.60757145],
       [24.60757145, 12.89705497]])

#### ii)

In [213]:
A=np.array([[8.46,-0.68],[3.06,1.88]])
m=np.array([-4, -3])
Y=np.dot(A,X+m[:,np.newaxis])

np.cov(Y)

array([[72.04460624, 24.60757145],
       [24.60757145, 12.89705497]])

### b)

In [5]:
cov = np.cov(X)

cov

array([[1.00029828e+00, 2.28294316e-06],
       [2.28294316e-06, 1.00066333e+00]])

#### i)

In [217]:
mx=np.mean(X,axis=1)
Xn=(X.T-mx).T
Ctmp=Xn*Xn
Cx=Ctmp/(X.shape[1]-1)

Cx

array([[4.51596766e-09, 2.28439666e-09, 1.05966801e-08, ...,
        4.38444383e-08, 2.47842780e-12, 1.01413806e-09],
       [8.44948225e-09, 4.46955901e-09, 2.66435716e-08, ...,
        2.25363457e-08, 9.21282730e-08, 2.03669104e-08]])

#### ii)

In [218]:
Cx=np.cov(X.T,rowvar=False)

Cx

array([[ 1.00010166e+00, -2.75024030e-04],
       [-2.75024030e-04,  1.00035858e+00]])

#### iii)

In [219]:
Cx=np.cov(X.T,rowvar=False,ddof=0)

Cx

array([[ 1.00010164e+00, -2.75024025e-04],
       [-2.75024025e-04,  1.00035856e+00]])

#### iv)

In [4]:
Cx=np.cov(X,rowvar=False)

Cx

MemoryError: Unable to allocate 2.84 PiB for an array with shape (20000000, 20000000) and data type float64

# Preenchimento das Respostas

In [21]:
q001 = respostas['Q001']
q002 = respostas['Q002']
q003 = respostas['Q003']

### Exercício 1

In [26]:
q001[:, :] = 0

q001[0, 0] = 1
q001[1, 3] = 1
q001[2, 2] = 1

q001

array([[1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]])

### Exercício 2

In [28]:
q002[:, :] = 0

q002[0, 3] = 1
q002[1, 0] = 1
q002[2, 1] = 1
q002[3, 1] = 1

q002

array([[0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.]])

### Exercício 3

In [32]:
q003[:, :] = 0

q003[0, 2] = 1
q003[1, 1] = 1

q003

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.]])

In [34]:
respostas['Q001'] = q001
respostas['Q002'] = q002
respostas['Q003'] = q003

respostas

{'Q001': array([[1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.]]),
 'Q002': array([[0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]]),
 'Q003': array([[0., 0., 1., 0.],
        [0., 1., 0., 0.]]),
 'nome': 'Fábio Alexandre Cruz Silva Dias',
 'numero': 'A42921'}

In [36]:
pickle.dump(respostas,open('A42921_Ficha1_Respostas.p','wb'))

In [37]:
a = pickle.load(open('A42921_Ficha1_Respostas.p','rb'))

a

{'Q001': array([[1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.]]),
 'Q002': array([[0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]]),
 'Q003': array([[0., 0., 1., 0.],
        [0., 1., 0., 0.]]),
 'nome': 'Fábio Alexandre Cruz Silva Dias',
 'numero': 'A42921'}