In [25]:
import pickle
import numpy as np
from scipy.spatial import distance
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

In [26]:
respostas = pickle.load(open('A42921_Ficha2_Respostas.p','rb'))
respostas

{'Q001': array([[0., 0., 0., 1.],
        [1., 0., 0., 0.]]),
 'Q002': array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 'Q003': array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 'nome': 'Fábio Alexandre Cruz Silva Dias',
 'numero': 'A42921'}

## Exercício 1

In [27]:
D = pickle.load(open('A42921_Q001_data.p','rb'))
XTrain = D['Xtrain']
XTest = D['Xtest']
targetTrain = D['trueClassTrain']
targetTest = D['trueClassTest']

### a)

In [28]:
# a = [[1, -2], [1, 1]]

# m0=np.mean(XTest[:,targetTest==0],axis=1)
# m1=np.mean(XTest[:,targetTest==1],axis=1)
# m2=np.mean(XTest[:,targetTest==2],axis=1)

# X0=XTest-m0[:,np.newaxis]
# X1=XTest-m1[:,np.newaxis]
# X2=XTest-m2[:,np.newaxis]

# D0=np.sum(np.dot(X0.T, np.dot(a,X0)), axis=0)
# D1=np.sum(np.dot(X1.T, np.dot(a,X1)),axis=0)
# D2=np.sum(np.dot(X2.T, np.dot(a,X2)),axis=0)

# Dtotal=np.vstack((D0,D1,D2))

# #Classificar:
# estClass=np.argmin(Dtotal,axis=0)
# #confusion_matrix(targetTest, estClass)

# kNN=KNeighborsClassifier(n_neighbors=15, metric=estClass)

# kNN.fit(XTest.T, targetTest)
# resultados=kNN.predict(XTest.T)

# confusion_matrix(targetTest, resultados)

def getDist(x, y):
    a = np.array([[1, -2], [1, 1]])
    xn = x - y
    dist = np.dot(np.dot(xn.T, a), xn)
    return dist

kNN=KNeighborsClassifier(n_neighbors=15, metric=getDist)

kNN.fit(XTrain.T, targetTrain)
resultados=kNN.predict(XTest.T)

confusion_matrix(targetTest, resultados)

array([[176,   8,   0],
       [  7,  69,   0],
       [  0,   0, 189]], dtype=int64)

### b)

In [29]:
kNN=KNeighborsClassifier(n_neighbors=15)

kNN.fit(XTrain.T, targetTrain)
resultados=kNN.predict(XTest.T)

confusion_matrix(targetTest, resultados)

array([[177,   7,   0],
       [  6,  70,   0],
       [  0,   0, 189]], dtype=int64)

## Exercício 2

### a)

In [73]:
import scipy.spatial.distance as spd

X = np.array([[-1, 2, 1, -1, 2, 6, 8, 4, 6, 4], 
              [1, 1, 2, 3, 2, -1, 2, -1, 1, -1]])
classes = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

D=spd.squareform(spd.pdist(X.T, 'cosine'))
D.astype(np.uint8)

m0=np.mean(X[:,classes==0],axis=1) # array de (4,)
m1=np.mean(X[:,classes==1],axis=1)
#Calcular calcular distancias das 3 m ˆ edias a todos os pontos: ´
X0=X-m0[:,np.newaxis] #m0, agora com dim. (4,1)
D0=np.sqrt(np.sum(X0*X0,axis=0))
X1=X-m1[:,np.newaxis] #m0, agora com dim. (4,1)
D1=np.sqrt(np.sum(X1*X1,axis=0))

#Construir matriz de distancias (3 ˆ × 150)
Dtotal=np.vstack((D0,D1))
#Classificar:
estClass=np.argmin(Dtotal,axis=0)
confusion_matrix(classes, estClass)

array([[5, 0],
       [0, 5]], dtype=int64)

### b)

In [76]:
print(m0)
print(m1)

[0.6 1.8]
[5.6 0. ]


## Exercicio 3)

In [115]:
D = pickle.load(open('A42921_Q003_data.p','rb'))
trueClass = D['trueClass']
estClass = D['estClass']

a = confusion_matrix(trueClass, estClass)

precision = a[0, 0] / (a[0, 0] + a[1, 0])
recall = a[0, 0] / (a[0, 0] + a[0, 1])

p_mais_r = precision + recall
p_vezes_r = precision * recall

b = 2 * p_vezes_r / p_mais_r
print(b)

FP = 51 / (51 + 189)
print(FP)

a

0.830622009569378
0.2125


array([[434, 126],
       [ 51, 189]], dtype=int64)

# Preenchimento das Respostas

In [30]:
q001 = respostas['Q001']
q002 = respostas['Q002']
q003 = respostas['Q003']

### Exercício 1

In [31]:
q001[:, :] = 0

q001[0, 3] = 1
q001[1, 0] = 1

q001

array([[0., 0., 0., 1.],
       [1., 0., 0., 0.]])

### Exercício 2

In [81]:
q002[:, :] = 0

q002[0, 2] = 1
q002[1, 3] = 1
q002[2, 0] = 1
q002[3, 2] = 1
q002[4, 3] = 1

q002

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Exercício 3

In [116]:
q003[:, :] = 0

q003[0, 0] = 1
q003[1, 3] = 1
q003[2, 3] = 1

q003

array([[1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [117]:
respostas['Q001'] = q001
respostas['Q002'] = q002
respostas['Q003'] = q003

respostas

{'Q001': array([[0., 0., 0., 1.],
        [1., 0., 0., 0.]]),
 'Q002': array([[0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 'Q003': array([[1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]]),
 'nome': 'Fábio Alexandre Cruz Silva Dias',
 'numero': 'A42921'}

In [118]:
pickle.dump(respostas,open('A42921_Ficha2_Respostas.p','wb'))

In [119]:
a = pickle.load(open('A42921_Ficha2_Respostas.p','rb'))

a

{'Q001': array([[0., 0., 0., 1.],
        [1., 0., 0., 0.]]),
 'Q002': array([[0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 'Q003': array([[1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]]),
 'nome': 'Fábio Alexandre Cruz Silva Dias',
 'numero': 'A42921'}