In [1]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
corpus=["you better start swimming or you’ll sink like a stone for the times they are a-changing",\
"the loser now will be later to win cause the times they are a-changing",\
"it’ll soon shake your windows and rattle your walls for the times they are a-changing"]

len(corpus)

3

In [6]:
print(corpus[0])
print(corpus[1])
print(corpus[2])

you better start swimming or you’ll sink like a stone for the times they are a-changing
the loser now will be later to win cause the times they are a-changing
it’ll soon shake your windows and rattle your walls for the times they are a-changing


In [9]:
cv = CountVectorizer().fit(corpus)
v = cv.transform(corpus)

In [10]:
v.toarray()

array([[0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 2, 0],
       [0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2,
        1, 1, 1, 0, 1, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
        1, 1, 0, 1, 0, 0, 1, 0, 2]], dtype=int64)

In [16]:
voc = cv.vocabulary_ #-> Organizado por ordem alfabética.
print(type(voc))
print(voc)

<class 'dict'>
{'you': 29, 'better': 3, 'start': 18, 'swimming': 20, 'or': 13, 'll': 10, 'sink': 16, 'like': 9, 'stone': 19, 'for': 6, 'the': 21, 'times': 23, 'they': 22, 'are': 1, 'changing': 5, 'loser': 11, 'now': 12, 'will': 26, 'be': 2, 'later': 8, 'to': 24, 'win': 27, 'cause': 4, 'it': 7, 'soon': 17, 'shake': 15, 'your': 30, 'windows': 28, 'and': 0, 'rattle': 14, 'walls': 25}


In [19]:
vn = cv.get_feature_names()
vn

['and',
 'are',
 'be',
 'better',
 'cause',
 'changing',
 'for',
 'it',
 'later',
 'like',
 'll',
 'loser',
 'now',
 'or',
 'rattle',
 'shake',
 'sink',
 'soon',
 'start',
 'stone',
 'swimming',
 'the',
 'they',
 'times',
 'to',
 'walls',
 'will',
 'win',
 'windows',
 'you',
 'your']

In [29]:
i = np.array(list(voc.values()))
words = list(voc.keys())

idx = np.argsort(i)
newD = {i:words[idx[i]] for i in range(len(words))}

In [34]:
newD

{0: 'and',
 1: 'are',
 2: 'be',
 3: 'better',
 4: 'cause',
 5: 'changing',
 6: 'for',
 7: 'it',
 8: 'later',
 9: 'like',
 10: 'll',
 11: 'loser',
 12: 'now',
 13: 'or',
 14: 'rattle',
 15: 'shake',
 16: 'sink',
 17: 'soon',
 18: 'start',
 19: 'stone',
 20: 'swimming',
 21: 'the',
 22: 'they',
 23: 'times',
 24: 'to',
 25: 'walls',
 26: 'will',
 27: 'win',
 28: 'windows',
 29: 'you',
 30: 'your'}

In [52]:
print(v.toarray())

print(v.toarray()[0, 29]) #Isto indica que a palavra 29 no newD aparece duas vezes.
print(newD[29]) #Neste caso "you"

[[0 1 0 1 0 1 1 0 0 1 1 0 0 1 0 0 1 0 1 1 1 1 1 1 0 0 0 0 0 2 0]
 [0 1 1 0 1 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 2 1 1 1 0 1 1 0 0 0]
 [1 1 0 0 0 1 1 1 0 0 1 0 0 0 1 1 0 1 0 0 0 1 1 1 0 1 0 0 1 0 2]]
2
you


#### Aula 22-11

In [32]:
import pickle
import matplotlib.pyplot as plt
import numpy as np

In [5]:
D = pickle.load(open("Laboratorio de Texto\imdbCriticas.p", 'rb'))

In [8]:
Docs = D['data']
y = D.target

In [33]:
print(np.unique(y))

[ 1  2  3  4  7  8  9 10]


In [29]:
Docs[0]

"Zero Day leads you to think, even re-think why two boys/young men would do what they did - commit mutual suicide via slaughtering their classmates. It captures what must be beyond a bizarre mode of being for two humans who have decided to withdraw from common civility in order to define their own/mutual world via coupled destruction.<br /><br />It is not a perfect movie but given what money/time the filmmaker and actors had - it is a remarkable product. In terms of explaining the motives and actions of the two young suicide/murderers it is better than 'Elephant' - in terms of being a film that gets under our 'rationalistic' skin it is a far, far better film than almost anything you are likely to see. <br /><br />Flawed but honest with a terrible honesty."

In [11]:
Docs[3]

'There are a lot of highly talented filmmakers/actors in Germany now. None of them are associated with this "movie".<br /><br />Why in the world do producers actually invest money in something like this this? You could have made 10 good films with the budget of this garbage! It\'s not entertaining to have seven grown men running around as dwarfs, pretending to be funny. What IS funny though is that the film\'s producer (who happens to be the oldest guy of the bunch) is playing the YOUNGEST dwarf.<br /><br />The film is filled with moments that scream for captions saying "You\'re supposed to laugh now!". It\'s hard to believe that this crap\'s supposed to be a comedy.<br /><br />Many people actually stood up and left the cinema 30 minutes into the movie. I should have done the same instead of wasting my time...<br /><br />Pain!'

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [38]:
tfidf = TfidfVectorizer().fit(Docs)

print(len(Docs))

40000


In [39]:
X = tfidf.transform(Docs)

print(X.shape)

(40000, 88214)


In [40]:
voc = tfidf.get_feature_names()

print(len(voc))
print(type(voc))

88214
<class 'list'>


In [41]:
print(voc[: 200])

['00', '000', '00000000000', '0000000000001', '00000001', '00001', '00015', '000dm', '001', '003830', '006', '0069', '007', '0079', '007s', '0080', '0083', '009', '0093638', '00am', '00o', '00pm', '00s', '01', '0126', '0148', '01pm', '02', '020410', '0230', '029', '03', '039', '04', '044', '05', '050', '06', '0615', '07', '07b', '08', '087', '089', '08th', '09', '0and', '0f', '0ne', '0r', '0s', '10', '100', '1000', '10000', '1000000', '10000000000', '10000000000000', '10000th', '1000lb', '1000s', '1000th', '1001', '1004', '100b', '100ft', '100ibs', '100k', '100min', '100mins', '100mph', '100s', '100th', '100times', '100x', '100yards', '101', '101st', '102', '102nd', '103', '104', '1040', '1040a', '1040s', '105', '1050', '106', '106min', '107', '108', '1080', '1080p', '109', '10_', '10am', '10ft', '10ish', '10k', '10lines', '10mil', '10mins', '10minutes', '10pm', '10s', '10th', '10x', '10yo', '10yr', '10yrs', '11', '110', '1100', '11001001', '1100ad', '110min', '110mph', '111', '112', '

In [42]:
print(voc[-200 : ])

['ziv', 'ziva', 'zivagho', 'ziyi', 'zizek', 'zizekian', 'zizola', 'zizte', 'zlatorog', 'zlotoff', 'zmed', 'zmeu', 'znaimer', 'znidarsic', 'zo', 'zobie', 'zod', 'zodiac', 'zodsworth', 'zoe', 'zoetrope', 'zoey', 'zoey101', 'zoeys', 'zohan', 'zohar', 'zohra', 'zoimbies', 'zoinks', 'zola', 'zolt', 'zoltan', 'zom', 'zombi', 'zombie', 'zombied', 'zombiefest', 'zombiefication', 'zombiefied', 'zombielike', 'zombies', 'zombietown', 'zombiez', 'zombification', 'zombified', 'zombs', 'zomcom', 'zomcon', 'zomedy', 'zomerhitte', 'zomg', 'zonadvd', 'zone', 'zone_', 'zoned', 'zones', 'zonfeld', 'zoning', 'zonked', 'zontar', 'zoo', 'zooey', 'zoog', 'zoolander', 'zoological', 'zoologist', 'zoologists', 'zoology', 'zoom', 'zoomed', 'zooming', 'zooms', 'zoos', 'zoot', 'zor', 'zora', 'zorak', 'zorba', 'zord', 'zords', 'zorich', 'zorie', 'zorina', 'zorn', 'zorro', 'zosch', 'zosh', 'zotoh', 'zouganelis', 'zounds', 'zow', 'zowee', 'zozo', 'zoé', 'zp', 'zsa', 'zschering', 'zsigmond', 'zsrr', 'zsrs', 'zu', 'zub

### Aula 29-11

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pickle

In [6]:
D = pickle.load(open("Laboratorio de Texto/imdbCriticas.p", "rb"))
Docs = D['data']

In [7]:
print(Docs[0])
Docs=[doc.replace('<br />', ' ') for doc in Docs]
print(Docs[0])

Zero Day leads you to think, even re-think why two boys/young men would do what they did - commit mutual suicide via slaughtering their classmates. It captures what must be beyond a bizarre mode of being for two humans who have decided to withdraw from common civility in order to define their own/mutual world via coupled destruction.<br /><br />It is not a perfect movie but given what money/time the filmmaker and actors had - it is a remarkable product. In terms of explaining the motives and actions of the two young suicide/murderers it is better than 'Elephant' - in terms of being a film that gets under our 'rationalistic' skin it is a far, far better film than almost anything you are likely to see. <br /><br />Flawed but honest with a terrible honesty.
Zero Day leads you to think, even re-think why two boys/young men would do what they did - commit mutual suicide via slaughtering their classmates. It captures what must be beyond a bizarre mode of being for two humans who have decided

In [9]:
import re

In [20]:
Docs2 = [re.sub(r'[^a-zA-ZÀ-ÿ]+', ' ', doc) for doc in Docs]

In [21]:
print(Docs2[0])

Zero Day leads you to think even re think why two boys young men would do what they did commit mutual suicide via slaughtering their classmates It captures what must be beyond a bizarre mode of being for two humans who have decided to withdraw from common civility in order to define their own mutual world via coupled destruction It is not a perfect movie but given what money time the filmmaker and actors had it is a remarkable product In terms of explaining the motives and actions of the two young suicide murderers it is better than Elephant in terms of being a film that gets under our rationalistic skin it is a far far better film than almost anything you are likely to see Flawed but honest with a terrible honesty 


In [22]:
s = Docs2[0]
s.split(' ')

['Zero',
 'Day',
 'leads',
 'you',
 'to',
 'think',
 'even',
 're',
 'think',
 'why',
 'two',
 'boys',
 'young',
 'men',
 'would',
 'do',
 'what',
 'they',
 'did',
 'commit',
 'mutual',
 'suicide',
 'via',
 'slaughtering',
 'their',
 'classmates',
 'It',
 'captures',
 'what',
 'must',
 'be',
 'beyond',
 'a',
 'bizarre',
 'mode',
 'of',
 'being',
 'for',
 'two',
 'humans',
 'who',
 'have',
 'decided',
 'to',
 'withdraw',
 'from',
 'common',
 'civility',
 'in',
 'order',
 'to',
 'define',
 'their',
 'own',
 'mutual',
 'world',
 'via',
 'coupled',
 'destruction',
 'It',
 'is',
 'not',
 'a',
 'perfect',
 'movie',
 'but',
 'given',
 'what',
 'money',
 'time',
 'the',
 'filmmaker',
 'and',
 'actors',
 'had',
 'it',
 'is',
 'a',
 'remarkable',
 'product',
 'In',
 'terms',
 'of',
 'explaining',
 'the',
 'motives',
 'and',
 'actions',
 'of',
 'the',
 'two',
 'young',
 'suicide',
 'murderers',
 'it',
 'is',
 'better',
 'than',
 'Elephant',
 'in',
 'terms',
 'of',
 'being',
 'a',
 'film',
 'that'

In [23]:
from nltk.stem import PorterStemmer

In [24]:
ps = PorterStemmer()
[ps.stem(w) for w in s.split(' ')]

['zero',
 'day',
 'lead',
 'you',
 'to',
 'think',
 'even',
 're',
 'think',
 'whi',
 'two',
 'boy',
 'young',
 'men',
 'would',
 'do',
 'what',
 'they',
 'did',
 'commit',
 'mutual',
 'suicid',
 'via',
 'slaughter',
 'their',
 'classmat',
 'it',
 'captur',
 'what',
 'must',
 'be',
 'beyond',
 'a',
 'bizarr',
 'mode',
 'of',
 'be',
 'for',
 'two',
 'human',
 'who',
 'have',
 'decid',
 'to',
 'withdraw',
 'from',
 'common',
 'civil',
 'in',
 'order',
 'to',
 'defin',
 'their',
 'own',
 'mutual',
 'world',
 'via',
 'coupl',
 'destruct',
 'it',
 'is',
 'not',
 'a',
 'perfect',
 'movi',
 'but',
 'given',
 'what',
 'money',
 'time',
 'the',
 'filmmak',
 'and',
 'actor',
 'had',
 'it',
 'is',
 'a',
 'remark',
 'product',
 'in',
 'term',
 'of',
 'explain',
 'the',
 'motiv',
 'and',
 'action',
 'of',
 'the',
 'two',
 'young',
 'suicid',
 'murder',
 'it',
 'is',
 'better',
 'than',
 'eleph',
 'in',
 'term',
 'of',
 'be',
 'a',
 'film',
 'that',
 'get',
 'under',
 'our',
 'rationalist',
 'skin',

In [26]:
' '.join([ps.stem(w) for w in s.split(' ')])

'zero day lead you to think even re think whi two boy young men would do what they did commit mutual suicid via slaughter their classmat it captur what must be beyond a bizarr mode of be for two human who have decid to withdraw from common civil in order to defin their own mutual world via coupl destruct it is not a perfect movi but given what money time the filmmak and actor had it is a remark product in term of explain the motiv and action of the two young suicid murder it is better than eleph in term of be a film that get under our rationalist skin it is a far far better film than almost anyth you are like to see flaw but honest with a terribl honesti '

In [30]:
Docs3 = [' '.join([ps.stem(w) for w in doc.split(' ')]) for doc in Docs2]

### Aula 04-12