In [1]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
corpus=["you better start swimming or you’ll sink like a stone for the times they are a-changing",\
"the loser now will be later to win cause the times they are a-changing",\
"it’ll soon shake your windows and rattle your walls for the times they are a-changing"]

len(corpus)

3

In [6]:
print(corpus[0])
print(corpus[1])
print(corpus[2])

you better start swimming or you’ll sink like a stone for the times they are a-changing
the loser now will be later to win cause the times they are a-changing
it’ll soon shake your windows and rattle your walls for the times they are a-changing


In [9]:
cv = CountVectorizer().fit(corpus)
v = cv.transform(corpus)

In [10]:
v.toarray()

array([[0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 2, 0],
       [0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2,
        1, 1, 1, 0, 1, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
        1, 1, 0, 1, 0, 0, 1, 0, 2]], dtype=int64)

In [16]:
voc = cv.vocabulary_ #-> Organizado por ordem alfabética.
print(type(voc))
print(voc)

<class 'dict'>
{'you': 29, 'better': 3, 'start': 18, 'swimming': 20, 'or': 13, 'll': 10, 'sink': 16, 'like': 9, 'stone': 19, 'for': 6, 'the': 21, 'times': 23, 'they': 22, 'are': 1, 'changing': 5, 'loser': 11, 'now': 12, 'will': 26, 'be': 2, 'later': 8, 'to': 24, 'win': 27, 'cause': 4, 'it': 7, 'soon': 17, 'shake': 15, 'your': 30, 'windows': 28, 'and': 0, 'rattle': 14, 'walls': 25}


In [19]:
vn = cv.get_feature_names()
vn

['and',
 'are',
 'be',
 'better',
 'cause',
 'changing',
 'for',
 'it',
 'later',
 'like',
 'll',
 'loser',
 'now',
 'or',
 'rattle',
 'shake',
 'sink',
 'soon',
 'start',
 'stone',
 'swimming',
 'the',
 'they',
 'times',
 'to',
 'walls',
 'will',
 'win',
 'windows',
 'you',
 'your']

In [29]:
i = np.array(list(voc.values()))
words = list(voc.keys())

idx = np.argsort(i)
newD = {i:words[idx[i]] for i in range(len(words))}

In [34]:
newD

{0: 'and',
 1: 'are',
 2: 'be',
 3: 'better',
 4: 'cause',
 5: 'changing',
 6: 'for',
 7: 'it',
 8: 'later',
 9: 'like',
 10: 'll',
 11: 'loser',
 12: 'now',
 13: 'or',
 14: 'rattle',
 15: 'shake',
 16: 'sink',
 17: 'soon',
 18: 'start',
 19: 'stone',
 20: 'swimming',
 21: 'the',
 22: 'they',
 23: 'times',
 24: 'to',
 25: 'walls',
 26: 'will',
 27: 'win',
 28: 'windows',
 29: 'you',
 30: 'your'}

In [52]:
print(v.toarray())

print(v.toarray()[0, 29]) #Isto indica que a palavra 29 no newD aparece duas vezes.
print(newD[29]) #Neste caso "you"

[[0 1 0 1 0 1 1 0 0 1 1 0 0 1 0 0 1 0 1 1 1 1 1 1 0 0 0 0 0 2 0]
 [0 1 1 0 1 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 2 1 1 1 0 1 1 0 0 0]
 [1 1 0 0 0 1 1 1 0 0 1 0 0 0 1 1 0 1 0 0 0 1 1 1 0 1 0 0 1 0 2]]
2
you
