In [29]:
import numpy as np
import matplotlib.pyplot as plt
import numpy.random as rd
import scipy.spatial.distance as spd
import sklearn.datasets as dt
from sklearn import metrics as mt
import pickle as pk
from sklearn.model_selection  import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

from sklearn.model_selection import cross_val_predict, cross_val_score
from sklearn.model_selection import KFold, StratifiedKFold

In [17]:
D = dt.load_iris()
X = D.data
y = D.target
D.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [20]:

# stratify -> quantidade semelhante para cada modelo por classe
X1, X2, y1, y2 = train_test_split(X, y, train_size=2/3, stratify=y) 

rf = RandomForestClassifier()
rf.fit(X1, y1)

print(rf.score(X2, y2))


y2e = rf.predict(X2)
print(y2e)
print(y2)

confusion_matrix(y2, y2e)

0.98
[0 1 1 1 2 1 2 1 1 0 2 2 1 2 0 0 2 1 0 2 2 1 1 1 1 2 2 1 0 0 2 0 0 0 0 0 0
 2 2 1 1 0 1 1 0 2 2 2 0 0]
[0 1 1 1 2 1 2 1 1 0 2 2 1 2 0 0 2 1 0 2 2 1 1 1 1 2 2 2 0 0 2 0 0 0 0 0 0
 2 2 1 1 0 1 1 0 2 2 2 0 0]


array([[17,  0,  0],
       [ 0, 16,  0],
       [ 0,  1, 16]], dtype=int64)

In [24]:
np.sum(y2e!=y2)
1 - np.sum(y2e!=y2)/50

0.98

In [28]:
rf = RandomForestClassifier()

cross_val_score(rf, X, y, cv=3) # treinou e testou k vezes o classificador

y2e = cross_val_predict(rf, X, y)
confusion_matrix(y, y2e)

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  2, 48]], dtype=int64)

In [32]:
cv = KFold(n_splits=3)
cross_val_score(rf, X, y, cv=cv) # treinar com dados sem embaralhar
cv = KFold(n_splits=5)
cross_val_score(rf, X, y, cv=cv) 

array([1.        , 1.        , 0.86666667, 0.93333333, 0.76666667])